live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/oxocarbon.toml"
]

[shell]
program = "/opt/homebrew/bin/fish"

[font]
size = 15
normal.family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"
