theme = "gruvbox_dark_hard"

[editor]
scrolloff = 10
cursorline = true
bufferline = "always"
end-of-line-diagnostics = "hint"
default-yank-register = "+"
true-color = true
idle-timeout = 0
completion-trigger-len = 1

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.indent-guides]
render = true

[keys.normal]
S-h = "goto_previous_buffer" 
S-l = "goto_next_buffer" 
C-s = ":wa"

[keys.insert]
C-space = "completion"

[keys.normal.space]
c = ":buffer-close"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "version-control",
  "diagnostics"
  ]
center = []
right = []
