theme = "gruvbox_dark_hard"

[editor]
scrolloff = 10
cursorline = true
bufferline = "always"
end-of-line-diagnostics = "hint"
default-yank-register = "+"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.indent-guides]
render = true

[keys.normal]
S-h = "goto_previous_buffer" 
S-l = "goto_next_buffer" 

[keys.insert]
C-space = "completion"

[keys.normal.space]
c = ":buffer-close"
