return {
  "folke/snacks.nvim",
  opts = {
    scroll = { enabled = false },
    animate = { enabled = false },
    image = { enabled = true },
    bigfile = { enabled = true },
    dashboard = { enabled = true },
    explorer = { enabled = true },
    gitbrowse = { enabled = true },
    indent = { enabled = true, animate = { enabled = false } },
    input = { enabled = true },
    notifier = { enabled = true },
    picker = { enabled = true, formatters = { file = { filename_first = true } } },
    quickfile = { enabled = true },
    rename = { enabled = true },
    scope = { enabled = true },
    statuscolumn = { enabled = true },
    words = { enabled = true },
  },
  keys = {
    -- Disable ALL LazyVim snacks keybindings (we define our own)
    { "<leader><space>", false },
    { "<leader>,", false },
    { "<leader>.", false },
    { "<leader>/", false },
    { "<leader>:", false },
    { "<leader>fb", false },
    { "<leader>fB", false },
    { "<leader>fc", false },
    { "<leader>fe", false },
    { "<leader>fE", false },
    { "<leader>ff", false },
    { "<leader>fF", false },
    { "<leader>fg", false },
    { "<leader>fn", false },
    { "<leader>fp", false },
    { "<leader>fr", false },
    { "<leader>fR", false },
    { "<leader>e", false },
    { "<leader>E", false },
    { "<c-/>", false },
    { "<c-_>", false },
  },
}
