[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[language-server.typescript-language-server.config.preferences]
importModuleSpecifierPreference = "relative"

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.mdpls]
command = "mdpls"
config = { markdown.preview.auto = false }

[[language]]
name = "markdown"
language-servers = ["mdpls", "marksman"]
comment-tokens = ["-", "+", "*", "- [ ]", ">"]
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]
config.settings.format.preview = true

[[language]]
name = "python"
language-servers = [ "ruff", "ty" ]
auto-format = true

[language-server.rust-analyzer]
config = { cargo = { allFeatures = true }, check = { command = "clippy" } }

[language-server.clangd]
command = "clangd"
args = ["--clang-tidy"]

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "yamlfmt", args = ["-"] }

[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]
auto-format = true



